mam_lectures/lectures/urls.py
from django.urls import path

from lectures.views import (CreateTaskView, TaskListView, UpdateTaskView,
                            hello_world)

app_name = 'lectures'

urlpatterns = [
    path('hello-world/', hello_world, name='hello'),
    path('hello-world/<int:times>/', hello_world, name='hello'),
    path('', TaskListView.as_view(), name='index'),
    path('create-task/', CreateTaskView.as_view(), name='create_task'),
    path('update-task/<int:task_id>/', UpdateTaskView.as_view(), name='update_task'),
]

mam_lectures/mam_lectures/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lectures.urls')),
    path('admin/', admin.site.urls),
]

mam_lectures/lectures/models.py
from django.db import models

from lectures.constants import EyeColor


class Organizer(models.Model):
    name = models.TextField("Name", null=False, blank=False)

    def __str__(self):
        return self.name

class Task(models.Model):
    title = models.TextField("Title")
    score = models.IntegerField("Maximum score")
    is_public = models.BooleanField("Is public", default=False)
    deadline = models.DateTimeField("Deadline", null=True, blank=True)
    author = models.ForeignKey(Organizer, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '{} ({})'.format(self.title, self.score)


EYE_COLOR_CHOICES = (
    (EyeColor.BLUE, "Blue"),
    (EyeColor.GREEN, "Green"),
    (EyeColor.BROWN, "Brown"),
)

class Student(models.Model):
    eye_color = models.CharField("Eye color", max_length=10, null=False, default=EyeColor.BROWN, choices=EYE_COLOR_CHOICES)
    solved_tasks = models.ManyToManyField(Task, related_name='students')

mam_lectures/lectures/admin/forms.py
from django import forms

from lectures.models import Task


class TaskAdminForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(),
        }

mam_lectures/lectures/forms.py
from django import forms
from django.core.validators import validate_email

from lectures.models import Task


class ExampleForm(forms.Form):
    """This form is not used anywhere, it's just a demonstration of form with custom validation."""
    title = forms.CharField(validators=[validate_email])
    score = forms.IntegerField(required=False)

    def clean_title(self):
        return self.cleaned_data['title'].lower()

    def clean_score(self):
        if self.cleaned_data['score'] < 0:
            raise forms.ValidationError('Score must be non-negative', code='negative')
        return self.cleaned_data['score']


class TaskForm(forms.ModelForm):
    """This is a good example of ModelForm."""
    class Meta:
        model = Task
        fields = ['title', 'score', 'is_public', 'author']
        widgets = {
            'title': forms.TextInput(),
        }

mam_lectures/lectures/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView

from lectures.forms import TaskForm
from lectures.models import Task


class TaskListView(TemplateView):
    """Template view that displays list of Tasks and some other info."""
    template_name = 'lectures/index.html'

    def get_context_data(self):
        context = {}
        context['user'] = {
            'name': 'honza',
            'login': 'stinovlas',
            'age': 30,
        }
        context['list'] = list(range(10))
        context['tasks'] = Task.objects.all()
        return context


class CreateTaskView(CreateView):
    """
    This view uses generic CreateView.

    We can find the corresponding template in `lectures/task_form.html`
    """
    model = Task
    fields = ['title', 'score', 'is_public']
    success_url = reverse_lazy('lectures:index')


class UpdateTaskView(TemplateView):
    """
    A little more complicated update view.

    We could also use generic UpdateView class, this is for illustrating purposes.
    """
    template_name = 'lectures/task_update.html'

    def get_context_data(self, task_id):
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(instance=task)
        return {'form': form}

    def post(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(request.POST)
        if form.is_valid():
            task.title = form.cleaned_data['title']
            task.score = form.cleaned_data['score']
            task.is_public = form.cleaned_data['is_public']
            task.author = form.cleaned_data['author']
            task.save()
            return HttpResponseRedirect(reverse('lectures:index'))
        else:
            return self.render_to_response({'form': form})


def hello_world(request, times=1):
    """Simple function based view."""
    return HttpResponse('Hello, world ({}x)!'.format(times))

mam_lectures/lectures/templates/lectures/base.html
<html>
<body>
    <h1>{% block title %}M&amp;M lectures{% endblock %}</h1>

    {% block content %}{% endblock %}
</body>
</html>

mam_lectures/lectures/templates/lectures/index.html
{% extends "lectures/base.html" %}

{% block title %}
    {{ block.super }}
    for talented organizers
{% endblock %}

{% block content %}

    <h2>Task list</h2>
        <a href="{% url 'lectures:create_task' %}">Add new task</a>

    {% for task in tasks %}
        <p>
            {{ task.title }}
            [{{ task.score }}]
            <a href="{% url 'lectures:update_task' task.pk %}">edit</a>
        </p>
    {% endfor %}

    <h2>Some other context data</h2>

    {% include 'lectures/list.html' %}

    <ul>
        <li>{{ user.name|capfirst }}</li>
        <li>{{ user.login }}</li>
        <li>{{ user.age }}</li>
    </ul>
{% endblock %}

mam_lectures/lectures/templates/lectures/list.html
<ul>
    {% for number in list %}
        {# Don't print zero #}
        {% if number != 0 %}
            <li>{{ number }}</li>
        {% endif %}
    {% empty %}
        There are no numbers left!
    {% endfor %}
</ul>

mam_lectures/lectures/templates/lectures/task_form.html
<form method="post">
    {% csrf_token %}
    <ul>
    {{ form.as_ul }}
    </ul>
    <input type="submit">
</form>

mam_lectures/lectures/templates/lectures/task_update.html
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>